### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by yhjsoar** [18-2-SKKU-OSS/2018-2-OSS-E6-new#21]
- 번역
- 그 외 

브랜치 나눠서 18-2-SKKU-OSS/2048.cpp 에서 pull request 보내기

**Comment by yhjsoar** [comment]
번역 pull request 보냄

**Comment by yjh1534** [comment]
statistics, scores 관련 pull request 보냄

**Comment by yhjsoar** [comment]
완료

**Comment by yhjsoar** [comment]
backtomenu branch pull request
