### ISSUE TITLE
게임 저장 후 게임을 종료하는 버튼이 없음.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6-new#3]
게임 저장 후 메뉴로 돌아가거나 게임을 종료하는 버튼을 만드는 것이 자연스러울 것 같음.

**Comment by yhjsoar** [comment]
이전에 완료한 이슈

**Comment by Leeinsu1** [comment]
정확하지 않은 이슈 등록으로 오해가 있어 다시 오픈함.

**Comment by Leeinsu1** [comment]
게임 중 메인 메뉴로 가는 버튼을 만들어 저장 후에 이 버튼을 누르면 저장 된 상태로 메뉴로 넘어가게 됩니다.
