### ISSUE TITLE
게임 스코어 저장이 4*4 에서밖에 되지 않음.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6-new#5]
다양한 크기의 게임 판 위에서 게임을하더라도, 스코어가 저장 될 수 있게 하면 좋을 것 같음.

**Comment by yjh1534** [comment]
gameboard 의 크기가 3이상 10 이하의 정수 N의 제곱으로 정해져 있습니다.
N의 크기에 따라 서로 다른 텍스트파일을 생성하여 점수를 저장하였습니다.
