### ISSUE TITLE
4*4의 게임 사이즈가 아니면 점수를 확인 할 수 없다.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6-new#8]
점수를 보고 싶을 때, 어떤 사이즈 게임판의 점수가 보고싶은지 고를 수 있게 하면 좋을 것 이다.

**Comment by yjh1534** [comment]
scoreboard에서 boardsize 선택하여 확인할 수 있도록 구현하였습니다.
