### ISSUE TITLE
statistics의 사이즈 구분이 되지 않고 있다.

### ISSUE THREAD

**Issue by Leeinsu1** [18-2-SKKU-OSS/2018-2-OSS-E6-new#9]

**Comment by yjh1534** [comment]
statistics을 boardsize에 따라 다르게 저장하였지만, statistics.txt파일은 새로 생성하지않고 미리 생성해둔 파일을 사용하도록 구현되어 있었습니다. 새로운 사이즈의 statistics가 생긴다면 새로운 txt파일을 생성하도록 구현하겠습니다.

**Comment by yjh1534** [comment]
이전에 사용한적이 없는 boardsize를 사용하여 게임을 진행하였다면, statistics를 저장할 때 새로운 statistics.txt파일을 생성하도록 구현하여 문제를 해결하였습니다.
